name: Teste

on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Ver arquivos
        run: ls -la

      - name: Rodar bot
        run: python bot.py