name: DEBUG TOTAL

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Mostrar arquivos
        run: |
          echo "LISTANDO ARQUIVOS:"
          ls -R

      - name: Ver conteúdo do bot.py
        run: |
          echo "CONTEUDO DO BOT:"
          cat bot.py

      - name: Rodar bot
        run: python bot.py