name: Bot Shopee Telegram

on:
  schedule:
    - cron: '0 */6 * * *'   # a cada 6 horas
  workflow_dispatch:         # permite rodar manualmente

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.8656227637:AAH4qVemew_e6O55Y2yc48x-Ko9eh8Ad-BI }}
          TELEGRAM_CHAT_ID:  ${{ secrets.https://t.me/achadinhosshopeebr4 }}
        run: |
          python bot.py