name: Teste Real

on:
  workflow_dispatch:

jobs:
  rodar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Listar arquivos
        run: ls -la

      - name: Rodar teste
        run: python teste.py